### ISSUE TITLE
How do I profile a program being replayed?

### ISSUE THREAD

**Issue by vi** [sidkshatriya/rd#11]
Naive `perf record --call-graph=dwarf rd rerun`, followed by `perf script | ./stackcollapse-perf.pl | ./flamegraph.pl` does not seem to produce useful results, showing mostly `rd`'s internals, not target program's.

Maybe I need to specify some symbols directories explicitly? Or maybe `rd` (or `rr`) can just output `perf`-compatible data on its own?

**Comment by sidkshatriya** [comment]
Yes, perf invoked in the manner you suggested will do a perf on `rd` and not the execution tree being recorded/replayed/rerun <== _(Edit: This is not correct. See below)_.  

`rd` does not have the ability to output perf compatible data itself. Also, one needs to think closely about what exactly you want to achieve here -- `rd` is basically ptracing the programs being recorded so its quite invasive and will change the characteristics of the program's run-time behavior significantly.

Requesting a comment from @khuey who may know more about this use case.

P.S. Also you should do `rd replay -a` instead of `rd rerun` if you don't want the replay via the debugger. `rd rerun` will be extremely slow as it will single step through the program (unless that is what you want).

**Comment by khuey** [comment]
rr/rd disturb the program timing enough (e.g. by locking everything to a single core) that performance profiling is unlikely to be particularly representative of real execution. This is not really a use case that we've tried to support. What are you hoping to learn?

If you *really* want to profile the tracee it is possible to do with a little legwork. You could, for example, record rr/rd replay and then use `perf script --pid <pid-of-the-tracee-during-replay>` to only process samples taken for the tracee.

**Comment by sidkshatriya** [comment]
Thanks @khuey for your very useful reply! Passing pid to `perf script` is a good idea.

So I checked this out some more and my earlier statement that perf will only profile `rd` and not the program being recorded/replay does not seem correct. `perf` seems to profile them also but the comments above regarding execution on single core only, invasive changes to run-time behavior of program etc. still hold true.

Here is a concrete example I played around with:
- `rd record -n gcc -- -o test test.c`
- `perf record --call-graph=dwarf rd replay -a` (here we are profiling replay)
- `perf script | grep cc1` gives you many lines like this `rd:cc1 1426143 308430.599953:     355826 cycles: `. Here `1426143` is the pid of `cc1` during replay. (cc1 is one of  the executables that is invoked by gcc)
- `perf script --pid 1426143`

The last line should see a lot of perf data relevant to `cc1` that you can process further. Hopefully this is a good starting point for your further explorations (I'm not very conversant with perf myself unfortunately).

Note that in this example I've disabled syscall buffering (`-n`). You can profile with or without syscall buffering depending on what you want.

**Comment by khuey** [comment]
>So I checked this out some more and my earlier statement that perf will only profile rd and not the program being recorded/replay does not seem correct. perf seems to profile them also but the comments above regarding execution on single core only, invasive changes to run-time behavior of program etc. still hold true.

`perf record <command>` will record the entire process tree *unless* you pass `--no-inherit` to it.

**Comment by sidkshatriya** [comment]
I think this query has been answered sufficiently. Please add any comments to this issue as necessary. Closing for now.
